from enum import Enum

class ProcessamentoFilterOption(str, Enum):
    PROCESSAMENTO_VINIFERAS = 'PROCESSAMENTO_VINIFERAS'
    PROCESSAMENTO_AMERICANAS_HIBRIDAS = 'PROCESSAMENTO_AMERICANAS_HIBRIDAS'
    PROCESSAMENTO_UVAS_MESA = 'PROCESSAMENTO_UVAS_MESA'
    PROCESSAMENTO_SEM_CLASSIFICACAO = 'PROCESSAMENTO_SEM_CLASSIFICACAO'

class ImportacaoFilterOption(str, Enum):
    IMPORTACAO_VINHO_MESA = 'subopt_01'
    IMPORTACAO_ESPUMANTE = 'subopt_02'
    IMPORTACAO_UVAS_FRESCAS = 'subopt_03'
    IMPORTACAO_UVAS_PASSAS = 'subopt_04'
    IMPORTACAO_SUCO_UVA = 'subopt_05'

class ExportacaoFilterOption(str, Enum):
    EXPORTACAO_VINHO_MESA = 'subopt_01'
    EXPORTACAO_ESPUMANTE = 'subopt_02'
    EXPORTACAO_UVAS_FRESCAS = 'subopt_03'
    EXPORTACAO_SUCO_UVA = 'subopt_04'