#PAGES
PRODUCAO = 'opt_02'
PROCESSAMENTO = 'opt_03'
COMERCIALIZACAO = 'opt_04'
IMPORTACAO = 'opt_05'
EXPORTACAO = 'opt_06'

#FILTERS PROCESSAMENTO
PROCESSAMENTO_VINIFERAS = 'subopt_01'
PROCESSAMENTO_AMERICANAS_HIBRIDAS = 'subopt_02'
PROCESSAMENTO_UVAS_MESA  = 'subopt_03'
PROCESSAMENTO_SEM_CLASSIFICACAO = 'subopt_04'

#FILTERS IMPORTACAO
IMPORTACAO_VINHO_MESA = 'subopt_01'
IMPORTACAO_ESPUMANTE = 'subopt_02'
IMPORTACAO_UVAS_FRESCAS = 'subopt_03'
IMPORTACAO_UVAS_PASSAS = 'subopt_04'
IMPORTACAO_SUCO_UVA = 'subopt_05'

#FILTERS EXPORTACAO
EXPORTACAO_VINHO_MESA = 'subopt_01'
EXPORTACAO_ESPUMANTE = 'subopt_02'
EXPORTACAO_UVAS_FRESCAS = 'subopt_03'
EXPORTACAO_SUCO_UVA = 'subopt_04'


